c_compiler:                # [linux]
  - gcc                    # [linux]
cxx_compiler:              # [linux]
  - gxx                    # [linux]
c_compiler_version:        # [linux]
  - 11.2.0                 # [linux]
c_stdlib_version:          # [linux]
  - 2.28                   # [linux]
cxx_compiler_version:      # [linux]
  - 11.2.0                 # [linux]
